// <copyright file="Program.cs" company="Some Company">
// Copyright (c)  All rights reserved.
// <author>Vitaliy Belyakov</author>
// </copyright>

namespace ChangingParamsWithEvent
{
    using System;

    /// <summary>
    /// Main class
    /// </summary>
    internal class Program
    {
        /// <summary>
        /// Main method
        /// </summary>
        private static void Main()
        {
            Console.Title = "Some test with events";

            // Set window params
            Console.WindowHeight = 40;
            Console.WindowWidth = 100;

            // Create Person instance and linking events
            Person drake = new Person("Drake", 29);
            drake.OnParamChanging += OnParamChanging;
            drake.OnParamChanged += OnParamChanged;
            drake.OnError += OnError;

            // Start values output
            Console.WriteLine(
                "Current Param ===> name: {0}; age: {1} ... Press Any key to continue",
                drake.Name,
                drake.Age);
            Console.WriteLine(new string('-', 30));

            // Name changing
            Console.Write("We testing change name ... input new name: ");
            drake.Name = Console.ReadLine();
            Console.WriteLine(new string('-', 30));

            // Age changing
            Console.Write("We testing change Age ... input new age: ");

            while (true)
            {
                int tempAge;

                if (int.TryParse(Console.ReadLine(), out tempAge))
                {
                    // Catch excep fron bad age if event not be worked
                    try
                    {
                        drake.Age = tempAge;
                        break;
                    }
                    catch (BadAgeException excep)
                    {
                        Console.WriteLine(excep.Message);
                    }
                }
                else
                {
                    Console.WriteLine("Bad input you must use only numbers");
                }
            }
            
            Console.ReadKey();
        }

        /// <summary>
        /// On changed event method
        /// </summary>
        /// <param name="sender">Some sender</param>
        /// <param name="e">Some getter</param>
        private static void OnParamChanged(object sender, ParamChangedArgs e)
        {
            Console.WriteLine("The settings were successfully changed\n" +
                string.Format(
                    "After name changing Param ===> name: {0}; age: {1} ... Press Any key to continue", 
                e.Name, 
                e.Age));
            Console.ReadKey();
        }

        /// <summary>
        /// Changing method
        /// </summary>
        /// <param name="sender">Some sender</param>
        /// <param name="e">Some getter</param>
        private static void OnParamChanging(object sender, ParamChangingArgs e)
        {
            if (e.NewAge != 0)
            {
                Console.WriteLine("Age was be changed from {0} to {1}", e.Age, e.NewAge);
            }

            if (!string.IsNullOrEmpty(e.NewName))
            {
                Console.WriteLine("Name was be changed from {0} to {1}", e.Name, e.NewName);
            }      
        }

        /// <summary>
        /// Error method
        /// </summary>
        /// <param name="sender">Some sender </param>
        /// <param name="e">Some getter </param>
        private static void OnError(object sender, ErrorArgs e)
        {
            Console.WriteLine("Bad age value... paremetr can't be changed..." +
                " \nThis message was generated by evenet");
        }
    }
}
